# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uoKhhl_YKSrG2gfrY1w71ZhhtdeePMU9
"""

import tensorflow as tf
import matplotlib.pyplot as plt

# Load Fashion MNIST dataset
from keras.datasets import fashion_mnist

# Load the Fashion MNIST dataset
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

# Scale down pixel values from 0-255 to 0-1
train_images = train_images / 255.0
test_images = test_images / 255.0

# Print dataset details
print(train_images.shape)
print(test_images.shape)
print(train_labels)

# Fashion MNIST class names
class_names = ['T-shirt/Top', 'Trouser', 'Pullover', 'Dress',
               'Coat', 'Sandal', 'Shirt', 'Sneaker',
               'Bag', 'Ankle Boot']

# Display first image
plt.imshow(train_images[1], cmap='gray')
plt.title(class_names[train_labels[1]])
plt.show()

# Defining neural network model
my_model = tf.keras.models.Sequential()

my_model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))

my_model.add(tf.keras.layers.Dense(128, activation='relu'))

my_model.add(tf.keras.layers.Dense(10, activation='softmax'))

# Compile the model
my_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
my_model.fit(train_images, train_labels, epochs=3)

# Evaluate the model
val_loss, val_acc = my_model.evaluate(test_images, test_labels)

print("Test Accuracy:", val_acc)