# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bw2geQ9DkwtrCtAQd4ncLMKdGq6HjijE
"""

#  Install KaggleHub
!pip install -q kagglehub


# Import libraries
import kagglehub
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Download dataset from Kaggle
path = kagglehub.dataset_download(
    "dakshbhalala/uci-air-quality-dataset"
)

print("Dataset downloaded to:", path)


# Find and load CSV
csv_file = [f for f in os.listdir(path) if f.endswith(".csv")][0]
file_path = os.path.join(path, csv_file)

# This Kaggle version is comma-separated
df = pd.read_csv(
    file_path,
    sep=",",
    decimal="."
)

# Remove completely empty columns
df = df.dropna(axis=1, how="all")

print("\nDataset loaded successfully!")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
print(df.head())

# Convert CO values to numbers
df['CO(GT)'] = pd.to_numeric(
    df['CO(GT)'],
    errors='coerce'
)

# In the original UCI dataset, -200 means missing value
df = df[df['CO(GT)'] != -200]

# Remove any remaining missing values
df = df.dropna(subset=['CO(GT)'])

# Extract CO values
data = df['CO(GT)'].values.reshape(-1, 1)

print("\nCO data shape:", data.shape)


# Normalize the data

scaler = MinMaxScaler()

data_scaled = scaler.fit_transform(data)

print("\nNormalized data:")
print(data_scaled[:5])

# Use previous 24 hours to predict next hour
time_steps = 24

X = []
y = []

for i in range(time_steps, len(data_scaled)):

    # Previous 24 values
    X.append(data_scaled[i-time_steps:i])

    # Next value
    y.append(data_scaled[i])

X = np.array(X)
y = np.array(y)

print("\nSequence shape:")
print("X:", X.shape)
print("y:", y.shape)


#Train-Test Split
train_size = int(len(X) * 0.8)

X_train = X[:train_size]
X_test = X[train_size:]

y_train = y[:train_size]
y_test = y[train_size:]

print("\nTraining data:", X_train.shape)
print("Testing data:", X_test.shape)

#Build LSTM model

model = Sequential()

model.add(
    LSTM(
        50,
        input_shape=(X_train.shape[1], X_train.shape[2])
    )
)

model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

print("\nModel:")
model.summary()


# Train the model

history = model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

# Make predictions
predicted = model.predict(X_test)


# Convert back to original CO values
predicted = scaler.inverse_transform(predicted)

actual = scaler.inverse_transform(y_test)

# Calculate RMSE and MAE
rmse = np.sqrt(
    mean_squared_error(actual, predicted)
)

mae = mean_absolute_error(
    actual,
    predicted
)

print("\n==============================")
print("MODEL PERFORMANCE")
print("==============================")
print("RMSE:", rmse)
print("MAE :", mae)

# 14. Plot Training and Validation Loss
plt.figure(figsize=(10, 5))

plt.plot(
    history.history['loss'],
    label='Training Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.title("LSTM Training and Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.show()


# Plot Actual vs Predicted
plt.figure(figsize=(12, 5))

plt.plot(
    actual,
    label='Actual CO'
)

plt.plot(
    predicted,
    label='Predicted CO'
)

plt.title("Air Quality CO Forecasting Using LSTM")
plt.xlabel("Time")
plt.ylabel("CO Concentration")
plt.legend()

plt.show()