# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vv9HnFrZN6X-Ag7msmFyNpDWJW2IDZxb
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import pandas as pd

# Load Fashion MNIST
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

# Normalize and reshape
x_train = x_train.reshape(-1, 784) / 255.0
x_test = x_test.reshape(-1, 784) / 255.0

# Model creation function
def create_model(lr):
    model = Sequential([
        Dense(128, activation='relu', input_shape=(784,)),
        Dense(64, activation='relu'),
        Dense(10, activation='softmax')
    ])

    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

learning_rates = [0.1, 0.01, 0.001]
results = []

for lr in learning_rates:
    model = create_model(lr)
    model.fit(x_train, y_train, epochs=5, batch_size=128, verbose=0)
    loss, acc = model.evaluate(x_test, y_test, verbose=0)
    results.append([lr, acc])

df = pd.DataFrame(results, columns=['Learning Rate', 'Accuracy'])
print(df)

plt.figure(figsize=(6,4))
plt.plot(df['Learning Rate'], df['Accuracy'], marker='o')
plt.xscale('log')
plt.xlabel("Learning Rate")
plt.ylabel("Accuracy")
plt.title("Learning Rate vs Accuracy (Fashion MNIST)")
plt.grid(True)
plt.show()



epochs_list = [5, 10, 20]
res = []

for ep in epochs_list:
    model = create_model(0.001)
    history = model.fit(
        x_train,
        y_train,
        validation_split=0.2,
        epochs=ep,
        batch_size=128,
        verbose=0
    )

    loss, acc = model.evaluate(x_test, y_test, verbose=0)
    res.append([ep, acc])

edf = pd.DataFrame(res, columns=['Epochs', 'Accuracy'])
print(edf)

plt.figure(figsize=(6,4))
plt.plot(edf['Epochs'], edf['Accuracy'], marker='o')
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Epochs vs Accuracy (Fashion MNIST)")
plt.grid(True)
plt.show()

# ------------------------------
model = create_model(0.001)

history = model.fit(
    x_train,
    y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=128
)

# Accuracy Plot
plt.figure(figsize=(6,4))
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training & Validation Accuracy")
plt.legend(['Train', 'Validation'])
plt.grid(True)
plt.show()

# Loss Plot
plt.figure(figsize=(6,4))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training & Validation Loss")
plt.legend(['Train', 'Validation'])
plt.grid(True)
plt.show()

# Test Accuracy
loss, accuracy = model.evaluate(x_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Load Dataset

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

class_names = [
    "T-shirt/top", "Trouser", "Pullover", "Dress",
    "Coat", "Sandal", "Shirt", "Sneaker",
    "Bag", "Ankle boot"
]


print("Training Data Shape:", x_train.shape)
print("Testing Data Shape:", x_test.shape)


# Display images

plt.figure(figsize=(8,5))

for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(x_train[i], cmap="gray")
    plt.title(class_names[y_train[i]])
    plt.axis("off")

plt.show()

# Normalize values

x_train = x_train.reshape(-1,784)/255.0
x_test = x_test.reshape(-1,784)/255.0

print("Training Shape:",x_train.shape)
print("Testing Shape:",x_test.shape)

def create_model(lr):

    model = Sequential([
        Dense(128, activation='relu', input_shape=(784,)),
        Dense(64, activation='relu'),
        Dense(10, activation='softmax')
    ])


    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

learning_rates = [0.1,0.01,0.001]

lr_results=[]


for lr in learning_rates:

    model=create_model(lr)

    model.fit(
        x_train,
        y_train,
        epochs=5,
        batch_size=128,
        verbose=0
    )


    loss,accuracy=model.evaluate(
        x_test,
        y_test,
        verbose=0
    )

    lr_results.append([lr,accuracy])


lr_df=pd.DataFrame(
    lr_results,
    columns=["Learning Rate","Accuracy"]
)


print(lr_df)

plt.plot(
    lr_df["Learning Rate"],
    lr_df["Accuracy"],
    marker='o'
)

plt.xscale("log")
plt.xlabel("Learning Rate")
plt.ylabel("Accuracy")
plt.title("Effect of Learning Rate")
plt.grid()
plt.show()

epochs_list=[5,10,20]

epoch_results=[]


for ep in epochs_list:

    model=create_model(0.001)


    model.fit(
        x_train,
        y_train,
        epochs=ep,
        batch_size=128,
        verbose=0
    )


    loss,accuracy=model.evaluate(
        x_test,
        y_test,
        verbose=0
    )


    epoch_results.append([ep,accuracy])


epoch_df=pd.DataFrame(
    epoch_results,
    columns=["Epochs","Accuracy"]
)


print(epoch_df)

plt.plot(
    epoch_df["Epochs"],
    epoch_df["Accuracy"],
    marker='o'
)

plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Effect of Epochs")
plt.grid()
plt.show()

model=create_model(0.001)


history=model.fit(
    x_train,
    y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=128
)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title("Accuracy Curve")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.legend(["Training","Validation"])
plt.grid()
plt.show()
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title("Loss Curve")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.legend(["Training","Validation"])
plt.grid()
plt.show()
loss,accuracy=model.evaluate(
    x_test,
    y_test
)

print("Test Accuracy:",accuracy)

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title("Loss Curve")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.legend(["Training","Validation"])
plt.grid()
plt.show()
loss,accuracy=model.evaluate(
    x_test,
    y_test
)

print("Test Accuracy:",accuracy)
prediction=model.predict(x_test)


plt.figure(figsize=(10,5))


for i in range(10):

    plt.subplot(2,5,i+1)

    plt.imshow(
        x_test[i].reshape(28,28),
        cmap="gray"
    )


    pred=np.argmax(prediction[i])


    plt.title(
        class_names[pred]
    )

    plt.axis("off")


plt.suptitle("Predicted Classes")
plt.show()
predicted_labels=np.argmax(
    prediction,
    axis=1
)


cm=confusion_matrix(
    y_test,
    predicted_labels
)


disp=ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=class_names
)


plt.figure(figsize=(10,8))

disp.plot(
    xticks_rotation=45
)

plt.title("Confusion Matrix")
plt.show()