# -*- coding: utf-8 -*-
"""assignment6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLnYja4eUqTavl9mnpFNubMA9i43xuMS
"""

import kagglehub
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import os
path = kagglehub.dataset_download(
    "mhantor/apple-leaf-diseases"
)
print("Path to dataset files:", path)
print("\nDataset contents:")
print(os.listdir(path))
BATCH_SIZE = 32
IMG_SIZE = (128, 128)

# Check folders inside downloaded dataset

folders = [
    f for f in os.listdir(path)
    if os.path.isdir(os.path.join(path, f))
]

print("\nFolders found:")
print(folders)
adjusted_path = path

if len(folders) == 1:

    possible_path = os.path.join(
        path,
        folders[0]
    )

    subfolders = [
        f for f in os.listdir(possible_path)
        if os.path.isdir(
            os.path.join(possible_path, f)
        )
    ]
    if len(subfolders) >= 2:
        adjusted_path = possible_path


print("\nUsing dataset path:")
print(adjusted_path)

# LOAD TRAINING DATA

train_ds = tf.keras.utils.image_dataset_from_directory(

    adjusted_path,

    validation_split=0.2,

    subset="training",

    seed=123,

    image_size=IMG_SIZE,

    batch_size=BATCH_SIZE
)

# LOAD VALIDATION DATA
val_ds = tf.keras.utils.image_dataset_from_directory(
    adjusted_path,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

#  GET CLASS NAMES
class_names = train_ds.class_names
print("\nDetected classes:")
print(class_names)
print(
    "\nNumber of classes:",
    len(class_names)
)
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().prefetch(
    buffer_size=AUTOTUNE
)
val_ds = val_ds.cache().prefetch(
    buffer_size=AUTOTUNE
)
num_classes = len(class_names)
model = models.Sequential([
    # Input
    layers.Input(
        shape=(128, 128, 3)
    ),
    # Normalize pixels
    layers.Rescaling(1./255),
    # CNN Layer 1
    layers.Conv2D(
        32,
        (3, 3),
        activation='relu'
    ),
    layers.MaxPooling2D(
        (2, 2)
    ),
    # CNN Layer 2
    layers.Conv2D(
        64,
        (3, 3),
        activation='relu'
    ),
    layers.MaxPooling2D(
        (2, 2)
    ),
    # CNN Layer 3
    layers.Conv2D(
        128,
        (3, 3),
        activation='relu'
    ),
    layers.MaxPooling2D(
        (2, 2)
    ),
    # Flatten
    layers.Flatten(),
    # Fully connected layer
    layers.Dense(
        128,
        activation='relu'
    ),
    # Dropout
    layers.Dropout(0.5),
    # Output layer
    layers.Dense(
        num_classes,
        activation='softmax'
    )
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
model.summary()
EPOCHS = 10
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
plt.figure(figsize=(12, 5))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(
    acc,
    label='Train Accuracy'
)
plt.plot(
    val_acc,
    label='Validation Accuracy'
)
plt.title('Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1, 2, 2)
plt.plot(
    loss,
    label='Train Loss'
)
plt.plot(
    val_loss,
    label='Validation Loss'
)
plt.title('Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

#  MODEL EVALUATION
import numpy as np
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

# Get true labels and predictions
y_true = []
y_pred = []

for images, labels in val_ds:

    predictions = model.predict(images, verbose=0)

    predicted_classes = np.argmax(
        predictions,
        axis=1
    )

    y_true.extend(labels.numpy())
    y_pred.extend(predicted_classes)


#  CLASSIFICATION REPORT
print("\nClassification Report:\n")
print(
    classification_report(
        y_true,
        y_pred,
        target_names=class_names
    )
)

# CONFUSION MATRIX
cm = confusion_matrix(
    y_true,
    y_pred
)
print("\nConfusion Matrix:\n")
print(cm)

# DISPLAY CONFUSION MATRIX
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=class_names
)
disp.plot(
    xticks_rotation=45
)
plt.title("Apple Leaf Disease Confusion Matrix")
plt.show()